# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-29104-apollo/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx485tffg1761-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/add_frac_bit.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/adder_div.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/func_select_add.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/hybird.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/LOD_function.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/lod.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/select_error_coeff_mul_64_16_bit.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/select_error_coeff_mul_64_8_bit.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/shifter.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/shifter_out_mul_div.v
      /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/tb_ezm_64.v
    }
      rt::read_vhdl -lib xil_defaultlib /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/top_wrapper.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/SIMDive/Hybrid_MULT_DIV/src/Vivado_Project.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-29104-apollo/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
