###############################################################
#  Generated by:      Cadence Innovus 21.16-s078_1
#  OS:                Linux x86_64(Host ID micro03)
#  Generated on:      Mon Aug  3 20:28:19 2026
#  Design:            oadm_dm
#  Command:           create_ccopt_clock_tree_spec -file ccopt_clock_tree.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 2.000ns) in timing_config functional_2ns([./apr_timing.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner dc_tt_typical -early -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_tt_typical -late -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss125_cworst -early -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss125_cworst -late -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss125_rcworst -early -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss125_rcworst -late -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss0_cworst -early -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss0_cworst -late -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss0_rcworst -early -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ss0_rcworst -late -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ssm40_cworst -early -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ssm40_cworst -late -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ssm40_rcworst -early -clock_tree clk 0.060
set_ccopt_property target_max_trans_sdc -delay_corner dc_ssm40_rcworst -late -clock_tree clk 0.060
set_ccopt_property source_max_capacitance -clock_tree clk 0.005
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 2

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:functional_2ns (sdc ./apr_timing.sdc)
create_ccopt_skew_group -name clk/functional_2ns -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/functional_2ns true
set_ccopt_property extracted_from_clock_name -skew_group clk/functional_2ns clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/functional_2ns functional_2ns
set_ccopt_property extracted_from_delay_corners -skew_group clk/functional_2ns {dc_tt_typical dc_ss125_cworst dc_ss125_rcworst dc_ss0_cworst dc_ss0_rcworst dc_ssm40_cworst dc_ssm40_rcworst dc_ff0_cbest dc_ff0_rcbest dc_ffm40_cbest dc_ffm40_rcbest dc_ff125_cbest dc_ff125_rcbest}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

