# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/vivado_prj/alu.cache/wt [current_project]
set_property parent.project_path /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/vivado_prj/alu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.3 [current_project]
set_property ip_output_repo /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/vivado_prj/alu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/add_frac_bit.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/adder_div.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/func_select_add.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/hybird.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/LOD_function.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/lod.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/select_error_coeff_mul_64_16_bit.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/shifter.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/shifter_out_mul_div.v
  /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/top_module.v
}
read_vhdl -library xil_defaultlib /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/SRC/top_wrapper.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/vivado_prj/alu.srcs/constrs_1/new/constr_1.xdc
set_property used_in_implementation false [get_files /afs/pd.inf.tu-dresden.de/users/muza153a/Desktop/alu/vivado_prj/alu.srcs/constrs_1/new/constr_1.xdc]


synth_design -top top_wrapper -part xc7vx485tffg1761-2 -directive AreaOptimized_high -control_set_opt_threshold 1 -max_bram 0 -max_uram 0 -max_dsp 0 -max_bram_cascade_height 0 -max_uram_cascade_height 0


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb"
